# -*- coding: utf-8 -*-
"""Model_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcFqo5PljfMPRC17aH1Ww-jsbT75vtta
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    matthews_corrcoef,
    confusion_matrix
)

df = pd.read_csv("adult.csv")

df.replace("?", np.nan, inplace=True)
df.dropna(inplace=True)

df["income"] = df["income"].map({
    "<=50K": 0,
    ">50K": 1
})

X = df.drop("income", axis=1)
y = df["income"]

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

def evaluate_model(model, model_name):

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    # For AUC
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:,1]
        auc = roc_auc_score(y_test, y_prob)
    else:
        auc = "Not Available"

    results = {
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "AUC": auc,
        "MCC": matthews_corrcoef(y_test, y_pred)
    }

    return results

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr_results = evaluate_model(lr, "Logistic Regression")

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt_results = evaluate_model(dt, "Decision Tree")

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn_results = evaluate_model(knn, "KNN")

from sklearn.naive_bayes import BernoulliNB

nb = BernoulliNB()
nb_results = evaluate_model(nb, "Naive Bayes")

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=50,
    random_state=42
)

rf_results = evaluate_model(rf, "Random Forest")

!pip install xgboost

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)

xgb_results = evaluate_model(xgb, "XGBoost")

results_list = [
    lr_results,
    dt_results,
    knn_results,
    nb_results,
    rf_results,
    xgb_results
]

results_df = pd.DataFrame(results_list)
results_df

results_df.to_csv("model_results.csv", index=True)

import joblib

joblib.dump(lr, "logistic.pkl")
joblib.dump(dt, "decision_tree.pkl")
joblib.dump(knn, "knn.pkl")
joblib.dump(nb, "naive_bayes.pkl")
joblib.dump(rf, "random_forest.pkl")
joblib.dump(xgb, "xgboost.pkl")
joblib.dump(scaler, "scaler.pkl")